### ISSUE TITLE
topology components not showing up on editor

### ISSUE THREAD

**Issue by yahanda** [Azure/video-analyzer-vscode-extension#106]
One day, each box of topology components suddenly disappeared in VS Code editor area (only connection settings are displayed), but it exists as a setting and works well. It's just a matter of appearance.
I tried restarting the PC, reinstalling the extension, and recreating a topology, but didn't resolve this issue.
Are there any causes of that that come to mind for you?

![image](https://user-images.githubusercontent.com/58975407/129029874-f28c272f-515f-4c31-899e-c6e38b10ef9b.png)

Thanks,
Yasu

**Comment by giakas** [comment]
The issues is fixed, and new version has been released.
